# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Disaster Preparation for Lazy People
email: hglass@tulane.edu
description: > # this means to ignore newlines until "baseurl:"

  How to prepare for a disaster if you're super lazy.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://barcamp-disaster-prep.github.io/" # the base hostname & protocol for your site
twitter_username: k6hey
github_username:  hmglass

# Build settings
markdown: kramdown
